services:
  database:
    image: postgres:14.12
    container_name: ajouchong-db
    environment:
      POSTGRES_DB:  ajouchong
      POSTGRES_USER:  chongchong
      POSTGRES_PASSWORD:  chong
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ajouchong-network

  backend:
    image: ajouchong-backend:latest
    build: .
    container_name: ajouchong-backend
    environment:
      SPRING_DATASOURCE_URL: ${SPRING_DATASOURCE_URL}
      SPRING_DATASOURCE_USERNAME: ${SPRING_DATASOURCE_USERNAME}
      SPRING_DATASOURCE_PASSWORD: ${SPRING_DATASOURCE_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    depends_on:
      - database
    ports:
      - "20232:8080"
    networks:
      - ajouchong-network

  nginx_proxy:
    image: nginx:1.21.5-alpine
    container_name: nginx_proxy
    ports:
      - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

volumes:
  postgres_data:

networks:
  ajouchong-network:
