spring:
  application:
    name: ajouchong
  profiles:
    active: prod
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  sql:
    init:
      mode: always

jwt:
  secret: ${secret}
  expiration_time: 86400000 #1일
server:
  port: 20232
