spring:
  application:
    name: ajouchong
  profiles:
    active: prod
  jpa:
    show-sql: true
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        show_sql: true


jwt:
  secret: ${secret}
  expiration_time: 86400000 #1일